export install=/usr/bin/install -c
export bash=/bin/bash
export awk=/opt/goke/ct/4.6.1/usr/bin/gawk
export grep=/bin/grep
export make=/usr/bin/make
export sed=/bin/sed
export libtool=/opt/goke/ct/4.6.1/usr/bin/libtool
export libtoolize=/opt/goke/ct/4.6.1/usr/bin/libtoolize
export objcopy=/usr/bin/objcopy
export objdump=/usr/bin/objdump
export readelf=/usr/bin/readelf
export patch=/usr/bin/patch
